version: '3'
services:
    app1:
        build:
            context: ./app1
            dockerfile: Dockerfile
        ports:
            - "8001:8001"

    app2:
        build:
            context: ./app2
            dockerfile: Dockerfile
        ports:
            - "8002:8002"

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - app1
            - app2